from abc import ABC, abstractmethod


class LLMClient(ABC):
    """Base interface for all LLM providers."""

    @abstractmethod
    def ask(self, question: str, context: str) -> str:
        """Return an answer generated by the language model."""
        pass